### PR TITLE
Copy Eclipse.icns

### PR DESCRIPTION
**Pull request by merks**
- Copied from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/icons/Eclipse.icns which as changed late last year.

https://github.com/eclipse-packaging/packages/issues/251

### CODE REVIEW

**Comment by merks** [comment]
@jonahgraham 

I just blindly copied the file over.  I don't know how to verify the contents.

**Comment by jonahgraham** [comment]
That looks like the right way to do this. @BeckerWdf had contributed the updates in #77 and I hadn't noticed that he provided further updates to platform later. Thanks @merks for handling this.

@BeckerWdf I assume that just copying them was correct, but I don't have easy access to a mac machine, nor do I know what to look for. Please let me know if you think there is more to do here.

**Comment by BeckerWdf** [comment]
> @BeckerWdf I assume that just copying them was correct, but I don't have easy access to a mac machine, nor do I know what to look for. Please let me know if you think there is more to do here.

Yes. That's correct. I can test once you have build ready.

**Comment by jonahgraham** [comment]
Thanks @BeckerWdf The staging builds are ready now - https://download.eclipse.org/technology/epp/staging/ - and the full M1 will be available on Jan 9. Let me know if you want me to notarize the staging build.

**Comment by BeckerWdf** [comment]
> Thanks @BeckerWdf The staging builds are ready now - https://download.eclipse.org/technology/epp/staging/ - and the full M1 will be available on Jan 9. Let me know if you want me to notarize the staging build.

The staging build looks good. 

But can you tell who the ICNS did change? You write:
>and I hadn't noticed that he provided further updates to platform later.

What change do you mean?

**Comment by merks** [comment]
I believe he's referring to your update from December 15th if I recall correctly in the Platform.  I.e., I looked at the history of the file mentioned in the EPP steps, assumed that this (your) change wasn't incorporated into EPP yet, and figured if I copy it, git will tell me if it's changed.  So I copied it and committed it.

**Pull request merged**
