### PR TITLE
Specify VM options on Windows to use the system certificate store.

### PR DESCRIPTION
**Pull request by merks**
- -Djavax.net.ssl.trustStoreType=Windows-ROOT
- -Djavax.net.ssl.trustStore=NONE

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/929

### CODE REVIEW

**Comment by merks** [comment]
@jonahgraham @sratz 

I think we should go with this...

**Review by jonahgraham — APPROVED** [review]
I approve this, although ideally it should be added to platform/sdk in the same release. This PR also saves me the work in this release step: https://github.com/eclipse-packaging/packages/blob/3392fc7506f1433e5a0fb822372f20eefa9804a5/RELEASING.md#L43

Is this worthy of a N&N entry in https://github.com/eclipse-packaging/packages/blob/3392fc7506f1433e5a0fb822372f20eefa9804a5/CHANGELOG.md#L8

**Comment by merks** [comment]
> I approve this, although ideally it should be added to platform/sdk in the same release. This PR also saves me the work in this release step:
> 
> https://github.com/eclipse-packaging/packages/blob/3392fc7506f1433e5a0fb822372f20eefa9804a5/RELEASING.md#L43
> 

Yes, the SDK product should have these same options and that was overlooked. Good catch.

> Is this worthy of a N&N entry in
> 
> https://github.com/eclipse-packaging/packages/blob/3392fc7506f1433e5a0fb822372f20eefa9804a5/CHANGELOG.md#L8

Yes, I think we should mention that small but significant change!

**Comment by sratz** [comment]
I successfully tested M2 with a corporate-internal update site with custom certificate. 👍

**Comment by sratz** [comment]
So a few months have passed and while this certainly improved the situation in many corporate environments, it appears in others this has made it worse:

There appear to be environments in which the trusted third-party root CA list is heavily stripped down, e.g. are missing Let's Encrypt.

In those environments the reverse is now necessary and the .ini parameters need to be manually removed.

Looks like browsers are also dealing with the same and have changed their approch:
https://learn.microsoft.com/en-us/deployedge/microsoft-edge-security-cert-verification
They now always use a **combination** of roots CAs from the operating system **and** their own trusted roots.

Sadly, it's not possible to tell the JVM to use a union of multiple trust stores via `-Djavax.net.ssl....` parameters.

The proper solution would be to programmatically build an `SSLContext` with a custom `TrustStore` as I have suggested back in https://www.eclipse.org/lists//cross-project-issues-dev/msg17927.html.

https://github.com/eclipse-platform/eclipse.platform/discussions/680 / https://github.com/eclipse-platform/eclipse.platform/pull/1716 go in the same direction, although way too heavyweight IMHO.

**Comment by sratz** [comment]
> It sounds like this needs to happen before Eclipse app starts to ensure the correct context is in place before any early accesses are done, i.e. in Equinox somewhere early on. Does Equinox/felix/OSGI have anything like this?

I suppose we'd need to do this during startup of one of the bundles with the lowest startup level:
https://github.com/eclipse-packaging/packages/blob/master/packages/org.eclipse.epp.package.java.product/epp.product#L70-L76

**Pull request merged**
