### PR TITLE
Update the splash to image with eclipse IDE in it

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-packaging/packages/issues/178

### CODE REVIEW

**Comment by merks** [comment]
@jonahgraham 

Here's how the compare in the IDE looks:

image

I don't suppose we need to wait for the verification build?

**Comment by nitind** [comment]
It's your call, but if this is to be our release build, I'd prefer to let all the checks run.

**Comment by howlger** [comment]
Looks good to me (I checked that the updated splash screen is in the same format and that it works in an IDE package on Windows 11).

**Comment by jonahgraham** [comment]
> I don't suppose we need to wait for the verification build?

No - I don't wait for verification builds on most things as the verification builds are really most useful when changing dependencies, tycho versions, included contents, etc. In the case of changing the splash screen the verification build isn't able to verify that the change was correct.

Note that we didn't even have verification builds for a while until we wanted to test some structural things.

FTR when doing bigger build system refactoring, I add my fork to the CI so that I can test my PR before merging it, see https://ci.eclipse.org/packaging/job/epp-jonahgraham-fork/ that pipeline stays disabled most of the time.

**Pull request merged**
