### PR TITLE
Upload bundle information in GitHub Actions

### PR DESCRIPTION
**Pull request by jonahgraham**

### CODE REVIEW

**Comment by jonahgraham** [comment]
The artifacts look good:

image

If someone needs additional files saved, they can add them to the workflow file:

https://github.com/eclipse-packaging/packages/blob/21f093a0af061dfeb32b8a3e733bcaf30c585eb4/.github/workflows/build.yml#L41

Note that I deliberately am not saving the full product as part of the build. That takes ~40GB per build and is rarely necessary.

**Comment by HannesWell** [comment]
Thanks! That's very helpful.

> Note that I deliberately am not saving the full product as part of the build. That takes ~40GB per build and is rarely necessary.

Sounds reasonable. I havn't found the limits on a quick search, but one probably cannot even save 40GB from a single upload/run, without special plans.

**Comment by jonahgraham** [comment]
> Sounds reasonable. I havn't found the limits on a quick search, but one probably cannot even save 40GB from a single upload/run, without special plans.

Could be as little as 500MB? https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#about-billing-for-github-actions:~:text=Minutes%20(per%20month)-,GitHub%20Free,2%2C000,-GitHub%20Pro

**Comment by HannesWell** [comment]
> > Sounds reasonable. I havn't found the limits on a quick search, but one probably cannot even save 40GB from a single upload/run, without special plans.
> 
> Could be as little as 500MB? https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#about-billing-for-github-actions:~:text=Minutes%20(per%20month)-,GitHub%20Free,2%2C000,-GitHub%20Pro

Yes looks like that. This is probably even combinded from all runs:
`The storage used by a repository is the total storage used by GitHub Actions artifacts and GitHub Packages.`

On the other hand, these limits only seem to apply to private repos:
`GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage for use with GitHub-hosted runners, depending on the account's plan. Any usage beyond the included amounts is controlled by spending limits.`

Any way, only uploading the bundles.info should work and gives already a lot of information 👍🏽

**Pull request merged**
