### PR TITLE
Always include slf4j.simple or m2e.logback in each package

### LINKED ISSUE #27: Update EPP for SLF4J v2 changes coming from platform
I am not sure exactly what needs to be done in EPP yet, see https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/588#issuecomment-1565332227 for a starting point and the N&N entry https://www.eclipse.org/eclipse/news/4.28/platform.php#slf4j.api-version-2

### PR DESCRIPTION
**Pull request by jonahgraham**
Fixes #27 specifically a follow up for #47:
https://github.com/eclipse-packaging/packages/pull/47#issuecomment-1692816329

### CODE REVIEW

**Comment by jonahgraham** [comment]
@HannesWell if you have a chance to review to see if this meets your expectation that would be great.

PS I added github actions in #49 so each package is now built on PRs:

image

**Comment by HannesWell** [comment]
> @HannesWell if you have a chance to review to see if this meets your expectation that would be great.

This looks perfectly fine. 👍🏽

> PS I added github actions in #49 so each package is now built on PRs:

That's very helpful.

**Comment by merks** [comment]
FYI, I tested generating the product catalogs against staging repositories:

- https://download.eclipse.org/technology/epp/staging/repository
- https://download.eclipse.org/staging/2023-09

Nothing was changed in the generator.   Then I created a committers installation with the installer and I see this in the bundles.info:
```
slf4j.simple,2.0.7,file:/D:/Users/test26/.p2/pool/plugins/slf4j.simple_2.0.7.jar,2,true
```
No errors are logged on startup.

So it looks good.

I also tried the Java package.  There slf4j.simple is not present but it has this instead:
```
ch.qos.logback.classic,1.4.11,file:/D:/Users/test26/.p2/pool/plugins/ch.qos.logback.classic_1.4.11.jar,2,true
```
It has this in the log:

image

So I guess that's okay too.

**Comment by jonahgraham** [comment]
Thank you for testing that @merks.

It is expected that java, dsl, jee, rcp packages has logback instead of slf4j:

```xml
$ git grep -B1 org.eclipse.m2e.logback.feature **/epp.product
packages/org.eclipse.epp.package.dsl.product/epp.product-      <!-- either m2e.logback or slf4j.simple should be provided in each package -->
packages/org.eclipse.epp.package.dsl.product/epp.product:      <feature id="org.eclipse.m2e.logback.feature" installMode="root"/>
--
packages/org.eclipse.epp.package.java.product/epp.product-      <!-- either m2e.logback or slf4j.simple should be provided in each package -->
packages/org.eclipse.epp.package.java.product/epp.product:      <feature id="org.eclipse.m2e.logback.feature" installMode="root"/>
--
packages/org.eclipse.epp.package.jee.product/epp.product-      <!-- either m2e.logback or slf4j.simple should be provided in each package -->
packages/org.eclipse.epp.package.jee.product/epp.product:      <feature id="org.eclipse.m2e.logback.feature" installMode="root"/>
--
packages/org.eclipse.epp.package.rcp.product/epp.product-      <!-- either m2e.logback or slf4j.simple should be provided in each package -->
packages/org.eclipse.epp.package.rcp.product/epp.product:      <feature id="org.eclipse.m2e.logback.feature" installMode="root"/>
```

In addition, if you run eclipsec.exe (or in a terminal on non-Windows) you should see with logback:

```
Aug. 26, 2023 9:40:59 A.M. org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic
Aug. 26, 2023 9:40:59 A.M. org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
```

and with slf4j:

```
Aug. 26, 2023 9:41:44 A.M. org.apache.aries.spifly.BaseActivator log
INFO: Registered provider org.slf4j.simple.SimpleServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle slf4j.simple
```

Which replaces the long standing message:

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```

**Comment by merks** [comment]
Very good.  That's what I see with the installer-created installations based on staging:
```
$committers-latest-staging/eclipse/eclipsec.exe
Aug. 26, 2023 3:46:15 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider org.slf4j.simple.SimpleServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle slf4j.simple

$java-latest-staging/eclipse/eclipsec.exe
Aug. 26, 2023 3:44:43 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic
Aug. 26, 2023 3:44:44 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
```

**Comment by HannesWell** [comment]
That's really great. 🎉 Thank you both for testing.

> In addition, if you run eclipsec.exe (or in a terminal on non-Windows) you should see with logback:
> 
> ```
> Aug. 26, 2023 9:40:59 A.M. org.apache.aries.spifly.BaseActivator log
> INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic
> ```

Btw. the ServletContainer is only necessary because Apache Aries cannot handle the edgy metadata of logback. I already provided a patch a while ago, but unfortunately nobody of the Aries maintainers even answered :/
- https://github.com/apache/aries/pull/233

**Pull request merged**
